spring:
  profiles:
   active: 
   - dev
   
---
server:
  port: 8201
spring:
  profiles: dev   #開發環境
  application:
    name: microservice-config-client
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
    
    
---
server:
  port: 8202
spring:
  profiles: test   #測試環境
  application:
    name: microservice-config-test
   
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/